---
apiVersion: v1
kind: Service
metadata:
  name: health-checks
  labels:
    app: health-checks
spec:
  ports:
  - port: 8080
    name: http
    targetPort: 80
  selector:
    app: health-checks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-checks
  labels:
    app: health-checks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-checks
  template:
    metadata:
      labels:
        app: health-checks
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: health-checks
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 25
            timeoutSeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 12
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 6
          image: quay.io/frarodroc/health-checks:latest
          ports:
          - containerPort: 80

