---
apiVersion: v1
kind: ConfigMap
metadata:
  name: health-checks
  labels:
    app: health-checks
data:
  index.html: "Hello World!"
---
apiVersion: v1
kind: Service
metadata:
  name: health-checks
  labels:
    app: health-checks
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: health-checks
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-checks
  labels:
    app: health-checks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-checks
  template:
    metadata:
      labels:
        app: health-checks
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: health-checks
          readinessProbe:
            exec:
              command:
                - /tmp/script.sh
            initialDelaySeconds: 25
            timeoutSeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 12
          livenessProbe:
            exec:
              command:
                - /tmp/script.sh
            initialDelaySeconds: 20
            timeoutSeconds: 10
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 6
          image: bitnami/apache:latest
          volumeMounts:
            - name: health-checks
              mountPath: /app/
      volumes:
        - name: health-checks
          configMap:
            name: health-checks
