---
apiVersion: v1
data:
  htpasswd: YWRtaW46JDJ5JDA1JHFFeWx5WmhtQ0ljak4yN3JsUi5ybS5YTkNDM29hZWpaQy9wUnU3c1B0QkEuVXI3RjZwYkVHCg==
kind: Secret
metadata:
  name: htpasswd
  namespace: openshift-config
type: Opaque
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: htpasswd
    mappingMethod: claim
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpasswd
---
