---
kind: ConfigMap
apiVersion: v1
metadata:
  name: script
data:
  script.js: |-
    import http from 'k6/http';

    export default function () {
      http.get("http://httpd.apps.example.com");
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: k6
        args:
        - "run"
        - "--duration"
        - "60s"
        - "--vus"
        - "5000"
        - "/opt/k6/script.js"
        image: loadimpact/k6
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmpfs
          name: tempfs
        - name: script
          mountPath: /opt/k6/
      restartPolicy: Never
      volumes:
      - emptyDir:
          medium: Memory
        name: tempfs
      - name: script
        projected:
          sources:
            - configMap:
                name: script
