kind: Service
apiVersion: v1
metadata:
  name: hello-openshift
  namespace: hello-openshift
  labels:
    app: hello-openshift
spec:
  ports:
    - name: http-8080
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: hello-openshift
