apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: demo
  namespace: demo
spec:
  params:
    - default: demo
      name: APP_NAME
      type: string
    - default: src/main/docker/Dockerfile
      name: DOCKERFILE
      type: string
    - default: 'https://github.com/frarodroc/demo'
      name: GIT_REPO
      type: string
    - default: master
      name: GIT_REVISION
      type: string
    - default: 'image-registry.openshift-image-registry.svc:5000/demo/demo'
      name: IMAGE_NAME
      type: string
    - default: /
      name: PATH_CONTEXT
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: spring-boot-repackage
      runAfter:
        - fetch-repository
      taskRef:
        kind: ClusterTask
        name: spring-boot-repackage
      workspaces:
        - name: source
          workspace: workspace
    - name: buildah
      params:
        - name: DOCKERFILE
          value: $(params.DOCKERFILE)
        - name: IMAGE
          value: $(params.IMAGE_NAME)
      runAfter:
        - spring-boot-repackage
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: workspace
  workspaces:
    - name: workspace
