---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: size
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: size
  labels:
    app: size
spec:
  replicas: 1
  selector:
    matchLabels:
      app: size
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: size
        deploymentconfig: size
    spec:
      containers:
        - name: size
          image: image-registry.openshift-image-registry.svc:5000/size-1/size:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
