---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: lorem-ipsum-1
  namespace: istio-system
spec:
  host: lorem-ipsum-1.apps.cluster-pkhtl.pkhtl.sandbox209.opentlc.com
  to:
    kind: Service
    name: istio-ingressgateway
    weight: 100
  port:
    targetPort: https
  tls:
    termination: passthrough
  wildcardPolicy: None
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-lorem-ipsum
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-expertise-tree-app3
  namespace: ff0da6b6-6acf-3d79-b4c6-ce512f798714
spec:
  gateways:
  - mesh
  - istio-system/gw-lorem-ipsum
  hosts:
  - lorem-ipsum-1.apps.cluster-pkhtl.pkhtl.sandbox209.opentlc.com
  http:
  - match:
    - authority:
        prefix: lorem-ipsum-1.apps.cluster-pkhtl.pkhtl.sandbox209.opentlc.com
      port: 80
    name: default
    route:
    - destination:
        host: lorem-ipsum.lorem-ipsum-1
        port:
          number: 8080
        subset: lorem-ipsum
      weight: 100
---
kind: Service
apiVersion: v1
metadata:
  name: lorem-ipsum
spec:
  ports:
    - name: http-8080
      protocol: HTTP
      port: 8080
      targetPort: 8080
  selector:
    app: lorem-ipsum
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: lorem-ipsum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lorem-ipsum
  template:
    metadata:
      labels:
        app: lorem-ipsum
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: lorem-ipsum
          image: image-registry.openshift-image-registry.svc:5000/size-1/size:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
