---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: size
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
---
kind: Service
apiVersion: v1
metadata:
  name: size
  labels:
    app: size
spec:
  ports:
    - name: http-8080
      protocol: HTTP
      port: 8080
      targetPort: 8080
  selector:
    app: size
    deploymentconfig: size
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: size
  labels:
    app: size
spec:
  replicas: 1
  selector:
    matchLabels:
      app: size
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: size
        deploymentconfig: size
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: size
          image: image-registry.openshift-image-registry.svc:5000/size-1/size:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
