---
kind: Namespace
apiVersion: v1
metadata:
  name: httpd
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: httpd
  namespace: httpd
  labels:
    app: httpd
data:
  index.html: Hello World!
---
kind: Service
apiVersion: v1
metadata:
  name: httpd
  namespace: httpd
  labels:
    app: httpd
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: httpd
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: httpd
  namespace: httpd
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      volumes:
        - name: httpd
          configMap:
            name: httpd
      containers:
        - name: httpd
          image: httpd:2.4
          volumeMounts:
            - name: httpd
              mountPath: /usr/local/apache2/htdocs/
          ports:
            - containerPort: 8080
              protocol: TCP
